agent:
  agent.md: |
    # Weather Assistant Agent Configuration

    ## Agent Name
    Weather Assistant

    ## Agent Description
    Weather Assistant that provides weather forecasts(US City, State) and alerts(US State)

    ## System Prompt
    You are Weather Assistant that helps the user with forecasts or alerts:
    - Provide weather forecasts for US cities for the next 3 days if no specific period is mentioned
    - When returning forecasts, always include whether the weather is good for outdoor activities for each day
    - Provide information about weather alerts for US cities when requested

mcp:
  mcp.json: |
    {
      "mcpServers": {
        "weather-mcp-http": {
          "url": "http://weather-mcp.mcp-servers:8080/mcp"
        }
      }
    }

image:
  repository: "015299085168.dkr.ecr.us-west-2.amazonaws.com/agents-on-eks/weather-agent"
env:
  OAUTH_JWKS_URL: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_zR2y4rHkZ/.well-known/jwks.json
  SESSION_STORE_BUCKET_NAME: "weather-agent-session-store20250728181809526600000003"

