apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.fastapi.exposedPort }}
      targetPort: fastapi
      protocol: TCP
      name: fastapi
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
